### ISSUE TITLE
Ask to `terraform init` an uninitialized workspace

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-ls#106]
https://microsoft.github.io/language-server-protocol/specification#window_showMessageRequest

> The show message request is sent from a server to a client to ask the client to display a particular message in the user interface. In addition to the show message notification the request allows to pass actions and to wait for an answer from the client.

Not entirely sure about the UX on this, but may be worth exploring.

**Comment by paultyng** [comment]
We should probably ask to initialize entirely uninitialized workspaces or when we get that error from the Terraform binary. But we may be able to be a bit proactive about it, when there are providers in source that are not initialized or maybe the local mirror directories change, etc.

**Comment by radeksimko** [comment]
I think this might require _some_ help from the language server in relation to https://github.com/hashicorp/terraform-ls/issues/32 because the server will likely be the one that knows better/best _where_ it's suitable to `terraform init` a particular directory.

**Comment by BertelBB** [comment]
Is it possible to disable the initialization?
It is breaking the _hashicorp.terraform_ extension for me because I am opening a workspace in VSCode with multiple Terraform projects and the extension is trying to perform the initialization in the root directory of the workspace, which is not a Terraform project.

**Comment by radeksimko** [comment]
The error will not be reported as per https://github.com/hashicorp/terraform-ls/pull/171 from the next release (0.4.0; to be released in coming days). The schema is still necessary for most functionality (pretty much all except formatting), but we need to better understand where in the hierarchy could a folder be potentially `init`d, so we can hint this to the user - as opposed to just expect it in any directory that is being opened - that's what this issue is mainly about.

Supporting monorepo and other more complex hierarchies is something we plan to support as part of #32

**Comment by radeksimko** [comment]
As for the implementation details of this one, I realized that [the JSON RPC library](https://github.com/creachadair/jrpc2) we use doesn't seem to support server->client requests. It can only send notifications (without waiting for response), such as [`window/showMessage`](https://microsoft.github.io/language-server-protocol/specification#window_showMessage) via [`jrpc2.ServerPush()`](https://pkg.go.dev/github.com/creachadair/jrpc2?tab=doc#ServerPush).
