### ISSUE TITLE
Many `terraform-ls` processes spawned & high memory usage

### ISSUE THREAD

**Issue by WinstonN** [hashicorp/terraform-ls#1100]
### Server Version

```
❯❯❯ .vscode/extensions/hashicorp.terraform-2.24.3-linux-x64/bin/terraform-ls --version
0.29.3
```

### Terraform Version

```
❯❯❯ terraform -v
Terraform v1.1.9
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.3.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Client Version

```
Terraform Extension for Visual Studio Code HashiCorp Terraform
v2.24.3

Visual Studio Code
Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:26.920Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-52-generic
Sandboxed: No
```

### Expected Behavior
My system should not be impaired by High Memory Usage 

### Actual Behavior
My system was impaired becasue of High Memory Usage 

### Steps to Reproduce
1. Enter a directory with terraform code
2. Execute `code .`
3. Wait for 5 minutes

The image below shows I'm only using 9GB, but just before this my system exhausted 32GB
Perhaps the issue is too many processes spawned?

![terraform-ls](https://user-images.githubusercontent.com/1143789/198468149-035bd61a-3e77-4840-b5a0-bda23f4b2a43.png)

**Comment by dbanck** [comment]
Hi @WinstonN!

Thanks for taking the time to report this! The observed behavior is odd; there should be a maximum of one language server process running per VS Code window. However, here it looks like an LS process is spawned repeatedly, consuming all system memory and swap.

Judging from your steps, I assume you only have one VS Code window open? Can you share the [language server log output](https://github.com/hashicorp/terraform-ls/blob/main/docs/TROUBLESHOOTING.md) (if obtainable)?

**Comment by radeksimko** [comment]
To add to what Daniel said above, although there should be only one process, it appears that each one consumes ~4GB?

That sounds like very high memory usage - especially given that in the latest version you're running we only load the schemas which are actually used, so unless your VS Code workspace consists of many different providers or many different versions of the same large provider (e.g. `aws` pinned strictly to various different versions in different modules), then this is likely a bug.

Can you share some details about your VS Code workspace? e.g. providers used and versions?

You could also [gather the memory profile](https://github.com/hashicorp/terraform-ls/blob/main/docs/TROUBLESHOOTING.md#memory-profiling) but it may be better to first get to the bottom of why there are so many processes, as collecting this from one process is more straight-forward.

**Comment by WinstonN** [comment]
> VS Code workspace consists of many different providers or many different versions of the same large provider (e.g. aws pinned strictly to various different versions in different modules)

This is indeed the case

I have generated a terraform-ls-mem.prof - can you recommend a Linux (ubuntu) tool to read and interpret that file?

I have attached 2 log files generated with the command
```
/home/win/.vscode/extensions/hashicorp.terraform-2.24.3-linux-x64/bin/terraform-ls serve -log-file='/tmp/terraform-ls-{{pid}}.log'
```
And a screengrab pf htop after 5 minutes 

[terraform-ls-33056.log](https://github.com/hashicorp/terraform-ls/files/9892085/terraform-ls-33056.log)
[terraform-ls-33725.log](https://github.com/hashicorp/terraform-ls/files/9892086/terraform-ls-33725.log)
![1](https://user-images.githubusercontent.com/1143789/198736511-06296d5c-7724-499e-9180-5381ab1e3db2.png)

**Comment by radeksimko** [comment]
### High memory usage

The best we can do about the memory usage [of a single process] is that we can correlate _all_ `required_providers` entries throughout your VS Code workspace, and try to reproduce this on our end and then assess if there are any further opportunities for memory savings. In general, however, the memory usage will always be correlated with the amount of providers and/or versions of those providers. This can be especially problematic if you use constraints w/ (implied) equal sign such as `version = "4.36.1"` as opposed to other operators - e.g. `version = "~> 4.36"`.

I can cobble a small Go program for you to run against the hierarchy and collect this data, if you are willing to run it?

> I have generated a terraform-ls-mem.prof - can you recommend a Linux (ubuntu) tool to read and interpret that file?

In general you can use `go tool pprof`. However, your logs suggest that on at least two occasions, the process is shut down very quickly and doesn't do anything, so profiling these is unlikely to be fruitful as it's killed before it allocates any significant memory. I think we need to get to the bottom of why the processes are getting killed first.

### Constraints [best practices]

Unless you have a strong reason (e.g. avoiding a particular bug which you know affects you and isn't fixed in the latest provider version), I would encourage you to loosen the constraints a little bit - not only for the editor experience, but also for security and generally to ensure you receive latest patches.

In general, providers follow semantic versioning, which means that they shouldn't introduce breaking changes except between major versions (the first number), e.g. between `2.0.0` and `3.0.0`.

When you loosen these constraints, it's more likely that there will be more overlap between these requirements and the same provider schema can be reused - e.g. `2.5.0` provider still matches `~> 2.1.0` and `~> 2.3.0`.

More importantly, there is [dependency lock file](https://developer.hashicorp.com/terraform/language/files/dependency-lock) (available in Terraform 0.14+), which ensures that the exact same provider is downloaded by anyone running `terraform init` - making upgrades more intentional via `terraform init -upgrade`. Constraints in code solve _compatibility_ problem, lock file solves _reproducibility_ amongst other things.

--- 

### Too many processes

Based on the log - as mentioned - it appears something is killing the server for some reason. This could be either the client (VS Code extension) or something else on your system - but it's unlikely to be OOM situation since that would typically result in SIGKILL (9), whereas your processes are receiving SIGINT.

After disabling the output to log files (i.e. keeping it default, sent to STDERR), can you inspect all the log panes in VS Code and try to spot anything out of ordinary (i.e. any errors/warnings)? I'm especially interested in the `HashiCorp Terraform` one and `Log (extension host)`. Also - disabling any other extensions (especially ones which claim HCL or Terraform files) while debugging this may help.

![Screenshot 2022-10-31 at 09 31 13](https://user-images.githubusercontent.com/287584/198976655-b5e33458-7d49-4f4f-b40d-e1f989ff51dc.png)

The file logs may be useful too, but it would require inspecting _all_ log files for _all_ server processes. Based on your htop screenshot, there's more than two (I see 15) and I only see two log files attached.

**Comment by radeksimko** [comment]
@mschfh Would you mind sharing the whole log or the configuration involved? Or have you tried isolating the problem to a particular directory, which you could share? It's unfortunately unlikely we'll be able to find the root cause based on that one line of log.

You can also send the log to `radek <at> hashicorp.com` & use my PGP key at https://keybase.io/radeksimko to encrypt it, if you're worried about posting it publicly here.

--- 

@WinstonN Did you have a chance to read my suggestions & questions above?

**Comment by dbanck** [comment]
I looked into reproducing the spawning of multiple language server processes under Linux but have had no luck so far.

Just as a sanity check, can you run `ps aux | grep terraform-ls` and post a screenshot of `htop -t` (which enables the tree view). I've found the default `htop` output confusing because it also lists threads. That makes it look like there are multiple processes, but in reality, one language server process spawns multiple threads (go routines).

**Comment by radeksimko** [comment]
@mschfh I'd be still happy to trawl through a 1GB size, if you can share it, e.g. via Google Drive or similar file sharing service.

@WinstonN Just to set expectations - We will have to close this if we're unable to reproduce the problem and don't have any more details unfortunately. I'll circle back to this after holiday period in January and close it, if no further details are received.

**Comment by jwshieldsGetty** [comment]
I believe I'm experiencing an issue that is very similar to this one, or this exact issue itself.

I am using VSCode (using a Workspace) and have several hundred repositories cloned from my organization. I haven't performed a `terraform init` on [m]any of them, but when VSCode starts, the language server spends 30 minutes to upwards of two hours walking and indexing modules, and the output log is spewing hundreds of thousands of lines of "getting provider schema"
EX:
> `2022/12/21 10:33:06 provider_schema.go:279: PSS: getting provider schema (C:\src\Git\[redacted], registry.terraform.io/-/aws, )`

That said, I am only seeing one instance of the language server running. but it's consuming >1.6GiB of memory and >40% CPU on my machine.
While all this is happening, things like saving a `*.tf` file takes minutes, and during that time, there's a toast message from VSCode that says (my words) "waiting for terraform fmt" - but the files never get formatted. 

I'd be happy to share logs or more debug information if needed.
