### ISSUE TITLE
Make LS compatible with Terraform v0.13

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#111]
### Current Version

```
v0.2.1
```

### Use-cases

Terraform 0.13 will be released soon and users should be able to use LS with that version.

### Proposal

One known issue is different location of the lock file, which is currently set here

https://github.com/hashicorp/terraform-ls/blob/b0f90d054aae8837759ab2fb740f4dd93849f738/internal/terraform/schema/watcher.go#L46-L52

the new location is apparently `.terraform/plugins/selections.json` - which seems platform-agnostic, so that's positive, but we may not be able to just automatically look for that new path based on Terraform version, because `v0.13` doesn't seem to be moving the old lock file to the new location.

**Comment by paultyng** [comment]
Maybe you could just watch both versions for now?

**Comment by paultyng** [comment]
Since the beta is out now, probably need to bump the priority.

**Comment by apparentlymart** [comment]
Related to this, I notice that the language server is using `hashicorp/go-version`'s `Constraints.Check` method to verify that it's working with Terraform 0.12 or later:

https://github.com/hashicorp/terraform-ls/blob/4d7a0e86eb6f05f0a39eb7ce0fe2d4d9c328c5f9/internal/terraform/lang/parser.go#L49

Unfortunately `go-version` doesn't consider prerelease versions (like `0.13.0-beta1`) as matching version constraint unless they are specified exactly in the version constraint.

In order to avoid reporting beta versions as unsupported, perhaps instead it could be written as a comparison of `Version` values, like this:

```go
minimumVersion := version.Must(version.NewVersion("0.12.0")
tfVersion.GreaterThanOrEqual(minimumVersion)
```

IIRC the prerelease special case applies to `Constraints.Check` specifically, and doesn't affect the precedence results indicated by the `Version` methods.
