### ISSUE TITLE
Can't get .tf highlighting to work. Terraform

### ISSUE THREAD

**Issue by sojjan1337** [hashicorp/terraform-ls#1151]
Hi!

Auto-completion works fine but the color highlighting doesn't work for .tf files.

If i install = Plug 'https://github.com/jvirtanen/vim-hcl.git' i get the highlighting to work, but then my auto-completion don't work because my .tf changes from file-type "terraform" to "hcl".

I have also test .py. It works with both auto-completion and highlighting.

Thank in advance! :)

**Comment by dbanck** [comment]
Hi @sojjan1337,

You already described the problem very accurately.

We don't (and can't) ship a Terraform-specific grammar for syntax highlighting for vim with the language server. So you have to rely on third-party vim plugins for that. Unfortunately, the plugin you're using [overrides the filetypes](https://github.com/jvirtanen/vim-hcl/blob/1e1116c17a5774851360ea8077f349e36fc733c1/ftdetect/hcl.vim#L7-L8) for `.tf` and `.tfvars` files to `hcl` while the Terraform LS only works with `terraform` and `terraform-vars` filetypes.

There are multiple ways to solve this:
* You could try using something else like [vim-terraform](https://github.com/hashivim/vim-terraform) instead of [vim-hcl](https://github.com/jvirtanen/vim-hcl)
* You could download the [syntax file from vim-hcl](https://github.com/jvirtanen/vim-hcl/blob/1e1116c17a5774851360ea8077f349e36fc733c1/syntax/hcl.vim) and save it to your vim `syntax/` directory as `terraform.vim`.

Both solutions should give you syntax highlighting for Terraform files while keeping the language server features available.
