### ISSUE TITLE
Super-slow, character-by-character diagnostics since 0.29.3

### ISSUE THREAD

**Issue by wzyboy** [hashicorp/terraform-ls#1317]
### Language Server Version

0.31.3 (actually anything >= 0.29.3)

### Terraform Version

1.2.9

### Client Version

Neovim 0.9.1

### Terraform Configuration

```terraform
resource "aws_s3_bucket_lifecycle_configuration" "foo" {}
```

### Steps to Reproduce

1. Open editor
2. Type something
3. Watch the diagnostics appear slowly (see screen record below)

https://github.com/hashicorp/terraform-ls/assets/459384/ddb747dd-b011-427d-b78e-325837da7bfd

The clip was recorded with this minimal `init.vim` config:

```
call plug#begin('~/.vim/plugged')
Plug 'neovim/nvim-lspconfig'
call plug#end()

lua <<EOF
  require'lspconfig'.terraformls.setup{}
EOF
```

### Expected Behavior

The diagnostics appear smoothly.

### Actual Behavior

The diagnostics appear slowly.

### Gist

https://gist.github.com/wzyboy/248e70eb2d6a6f105354b7adca07ee32

### Workarounds

I tried downgrading terraform-ls to earlier versions. With some bisecting, the last known good version is 0.29.2. Since 0.29.3, the slowness starts.

### References

- At first I thought it's Neovim's issue so I reported there: https://github.com/neovim/neovim/issues/24133

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bcspragu** [comment]
I'm also experiencing this behavior (same as https://github.com/hashicorp/terraform-ls/issues/487) on the latest release. Like @wzyboy, running 0.29.2 solves the problem for me. I'm using Helix as an editor.

Happy to provide LSP logs if that's useful.

**Comment by rlees85** [comment]
Same problem on neovim. Its been like it for a long while now if not forever.

- Normally its varying degrees of painfully slow, on a good day its painfully slow and on a bad day you can make a cup of tea in the time it takes to process the fact you wrote a sentence.
- Very occasionally, the problem does not occur at all and the LSP works amazingly.

I also find that typing suggestions only work occasionally, normally its when the LSP isn't behaving slow. Not sure if its related or not. The LSP is 100% started when typing suggestions don't work as its running really slow and diagnostics are 'working'.

Until now I've just put up with it but I don't know if this is a problem with Neovim or this LSP although I do use ~10 other language servers for varying things and this is the only one that is barely usable - the others work great.

If theres anything I can do ie logs to help then please let me know. I also have to pipe neovim lsp logs to /dev/null due to the amount of noise created by the Terraform LS which is probably another issue...

**Comment by jpogran** [comment]
We know this has been a frustrating experience and appreciate your understanding while we gathered feedback and examples to diagnose this issue. We've created https://github.com/hashicorp/vscode-terraform/issues/1557 as a central place to see updates on what we are doing to address performance issues in terraform-ls in both the short and long term and pinned it to the repo. We'll be adding more detail there as we implement fixes. As we work on this we'll be recording the content and then closing the individual issues so that everyone has one place to look at instead of searching for individual tickets for updates.

**Comment by bcspragu** [comment]
Thanks for the update, and I'm happy to test out the opt-in performance profiling when it's ready, or just recompile `terraform-ls`  and gather `pprof` profiles, if that's useful.

Though for this particular issue, I don't think it's a question of people's workflows or the size of their projects or anything architectural, I think it's just a regular ole bug. Like "something blocking the main thread and doing redundant network requests" or similar. As @rlees85 wrote, this is "make a cup of tea" slow even on fairly run-of-the-mill Terraform projects. Plus, empirically the issue doesn't exist in `0.29.2`, and [the delta to `0.29.3`](https://github.com/hashicorp/terraform-ls/compare/v0.29.2...v0.29.3) contains a finite number of changes, one of which introduces this pathology.

Beyond this specific bug, I think something as straightforward as debounce ("don't run this analysis until Xms since the last keystroke") or cancelling existing analysis when new strokes come in could be a "quick" fix here.

**Comment by wzyboy** [comment]
I only pinpointed the bug to be introduced between 0.29.2 and 0.29.3, but as @bcspragu pointed out, there are only [43 commits](https://github.com/hashicorp/terraform-ls/compare/v0.29.2...v0.29.3) between the two releases.

I'm not familar with Golang, but someone with Golang expertise can use [`git bisect`](https://git-scm.com/docs/git-bisect) to find the exact commit that introduced the bug with only a few re-compilations of the Golang code.

It's not a performance improvement that is needed, it's a bug fix.

**Comment by rlees85** [comment]
> I only pinpointed the bug to be introduced between 0.29.2 and 0.29.3, but as @bcspragu pointed out, there are only [43 commits](https://github.com/hashicorp/terraform-ls/compare/v0.29.2...v0.29.3) between the two releases.
> 
> I'm not familar with Golang, but someone with Golang expertise can use [`git bisect`](https://git-scm.com/docs/git-bisect) to find the exact commit that introduced the bug with only a few re-compilations of the Golang code.
> 
> It's not a performance improvement that is needed, it's a bug fix.

your not wrong... I'm not a go expert really but I know enough to compile terraform-ls from source. Finding free time is awkward but i'll do it if no-one beats me to it. I can confirm 0.29.2 also fixes the problem for me though which is strange as I thought the problem has been ongoing for ages.

**Comment by dbanck** [comment]
We've just released `0.31.5` which contains two fixes (https://github.com/hashicorp/terraform-ls/pull/1369, https://github.com/hashicorp/terraform-ls/pull/1372) to address this issue.

With the fix, we should be back to 0.29.2 levels of CPU usage while maintaining the memory improvements of 0.29.3.

If you have the time, please give it a try and let us know how it works for you.

**Comment by bcspragu** [comment]
Happy to give this a test run, but it looks like no release since [v0.30.1](https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.1) contains compiled release artifacts.

**Comment by bcspragu** [comment]
Ah yes, apologies for not [RTFM](https://github.com/hashicorp/terraform-ls/blob/main/docs/installation.md). I'm running `0.31.5` and in preliminary testing, it's been super speedy, even on the slow hardware (spinning disk, decade old servers). I'll keep testing and poking and prodding it, but I think the issue might be fixed!

Looking at your linked fixes, I'm guessing that everyone in this thread is using non-VS Code (which may have different LSP behavior) editors and HDD storage (slow reads from disk). Thanks again for sorting this out!

**Comment by wzyboy** [comment]
I tried 0.31.5 release and I can confirm that the super-slow issue has been resolved! Thank you for the bug fix!

**Comment by rlees85** [comment]
Didn't need to write Terraform for a while but yes all god - thanks very much!!
