### ISSUE TITLE
Centralize diagnostics publishing

### ISSUE THREAD

**Issue by dbanck** [hashicorp/terraform-ls#1337]
### Language Server Version

v0.31.3

### Problem Statement

We currently publish diagnostics from two different locations:

In a module hook

https://github.com/hashicorp/terraform-ls/blob/b9eabdc32f40c9494787c3d982c6a5d1cc0f3d4d/internal/langserver/handlers/hooks_module.go#L153-L161

In the `didSave` handler when validate on save is enabled

https://github.com/hashicorp/terraform-ls/blob/b9eabdc32f40c9494787c3d982c6a5d1cc0f3d4d/internal/langserver/handlers/command/validate.go#L70-L75

With the introduction of early validation, we'll likely have a third location that won't have access to the diagnostics raised by `terraform valdiate`.

---

Part of https://github.com/hashicorp/vscode-terraform/issues/720

### Proposal

* Rework the module hooks, that only one is publishing diagnostics

### Related LSP methods

- textDocument/didSave
- textDocument/didChange
- textDocument/didOpen

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
This may be more related to https://github.com/hashicorp/terraform-ls/issues/1339 but one challenge with notifications triggered from `didSave` is that `didSave` generally does not make document changes, and hence it won't trigger the hooks currently.

This is kind of by design (at least within the LSP) but it does mean that we may have to find some way of synchronising `didSave` with hooks completion, in addition to persisting diagnostics (at least before they get published?).

The reason I think it's also related to https://github.com/hashicorp/terraform-ls/issues/1339 is because there is other work than just diagnostic publishing (such as telemetry sending) that could also run less frequently, maybe on save or within N seconds after the last didChange, depending on which comes first.

**Comment by dbanck** [comment]
Closed by #1361
