### ISSUE TITLE
*.tfvars file not showing syntax coloring

### ISSUE THREAD

**Issue by ubenmackin** [hashicorp/terraform-ls#148]
### Server Version

```
terraform-ls --version
0.3.2
```

### Terraform Version

```
terraform -v
Terraform v0.12.26
```

### Client Version

```
VSCode on Windows 10 with the new terraform extension (2.0.0-rc2)
```

### Terraform Configuration Files

local.tfvars

```hcl
// Environment variables
environment       = "dev"
subscription_id   = "XXXXXXXXXXXXXXXXXXXXXX"
azure_developer   = "XXXXX@XXXXX.com"

// This name is applied to all resources created
prefix = "myprefix"

// First is Primary and second is Backup
instance        = ["primary", "secondary"]
instance_short  = ["1", "2"]
location        = ["East US", "West US"]
timezone        = ["Eastern Standard Time", "Pacific Standard Time"]
location_alt    = ["eastus", "westus"]
rg_count        = 1 // 1 or 2; 1 builds a single primary RG, 2 builds primary and secondary
```

### Log Output

N.A.

### Expected Behavior

Syntax coloring should work

### Actual Behavior

.tfvars file isn't recognized by the language server. There is no indication in the logs that is trying to read the file, almost as if the file type isn't picked up as a valid one.

### Steps to Reproduce

1. Open a folder in IDE
2. Open a file name local.tfvars
3. No syntax coloring is observed.

**Comment by radeksimko** [comment]
Hi @ubenmackin 
Thank you for trying out the release candidate of the extension.

Generally syntax highlighting is done on the client side - i.e. by the extension directly, so that's not something server could implement (yet) as the [LSP](https://microsoft.github.io/language-server-protocol/) (protocol used between client/IDE and the server) doesn't specify that. There is a PR which should enable syntax highlighting of tfvars: https://github.com/hashicorp/vscode-terraform/pull/349

As for the language server features related to tfvars - I believe this is already covered under https://github.com/hashicorp/terraform-ls/issues/50

With that in mind I'm going to close this issue in favour of the linked one and the PR.
