### ISSUE TITLE
Support provider aliases and 0.13 identities

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-ls#164]
### Terraform Version

This affects 0.13 mostly, but to a lesser degree 0.12

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    null = {
      source = "hashicorp/null"
      version = "2.1.2"
    }
    null2 = {
      source = "paultyng/null"
      version = "0.1.0"
    }
  }
}

provider "null2" {
    alias = "null3"
}

resource "null_resource" "foo" {

}

resource "null_resource" "bar" {
    provider = null2
}

resource "null_resource" "baz" {
    provider = null2.null3
}
```

### Expected Behavior

Auto-completion with multiple providers that have conflicting resource names should include the addition of the `provider = ` attribute.

### Actual Behavior
I believe resources with the same type names currently are just overwritten by the last one in. This can also probably be observed in 0.12 with `google` and `google-beta`.

**Comment by paultyng** [comment]
https://github.com/hashicorp/terraform-config-inspect does not yet support listing out possible aliases, only ones in used on resources, so that will need to be addressed upstream (or parsed out manually).

**Comment by radeksimko** [comment]
Just realized that provider block completion doesn't work at all with 0.13, since we're looking e.g. for `aws`, but 0.13 indexes that as `registry.terraform.io/hashicorp/aws`.

Also provider labels are completed with the FQN too, which is wrong:

![Screenshot 2020-06-30 at 19 42 54](https://user-images.githubusercontent.com/287584/86164801-429eec80-bb0a-11ea-8a53-15d07b147ee4.png)
