### ISSUE TITLE
Huge memory usage

### ISSUE THREAD

**Issue by cveld** [hashicorp/terraform-ls#1730]
### Language Server Version

not sure

### Terraform Version

terraform v1.8.1 on windows_amd64

### Client Version

vscode 1.90.0 terraform extension 2.30.2

### Terraform Configuration

```terraform
I think it is a general problem
```

### Steps to Reproduce

Just open vscode and wait for the memory consumption to kick in during the day.

### Expected Behavior

Little memory usage

### Actual Behavior

Huge memory usage

![image](https://github.com/hashicorp/terraform-ls/assets/6196260/e15e5d02-8fb6-4aa4-8527-b1706f4c7124)

### Workarounds

I occasionally kill the terraform-ls.exe processes and start over.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
We've just released `v2.31.2024061114`, which ships with a re-architected language server for improved performance and resource usage ([terraform-ls#1667](https://github.com/hashicorp/terraform-ls/issues/1667)). The language server will now start up much faster and use fewer resources, especially on larger workspaces.

In VS Code, you can opt in to the extension preview:
![CleanShot 2024-06-17 at 12 18 50@2x](https://github.com/hashicorp/vscode-terraform/assets/45985/2e23ba89-e070-4b75-a531-9d3ee3965cdc)

If you have the time, please give it a try and let us know how it works for you. We have tested this with workspaces of different sizes, but still expect some bugs due to the wide variety of configurations. Your feedback is greatly appreciated.
