### ISSUE TITLE
Variables (auto suggest/Peak)

### ISSUE THREAD

**Issue by msaraceno** [hashicorp/terraform-ls#191]
Prior 2.0.0 extension when referencing a variable in a resource block it would use intellisense and suggest variables that were declared, this no longer happens also if you hovered your mouse over a variable that you set in a resource block it would show the value of the variable. These were both useful features. This only worked when you used TF  <=0.11.14 syntax. I am running extension 2.0.2. I would like this feature to be supported with Terraform 0.12.x

**Comment by radeksimko** [comment]
Hi @msaraceno 
This sounds like a feature that would better be implemented on the language server side - which is why I transferred the issue here.

Just to clarify - are you looking for completion for variable references? e.g.

```terraform
resource "bla_blah" "name" {
  attribute = var.<HERE>
}
```

If so then that's something we do plan to implement as part of https://github.com/hashicorp/terraform-ls/issues/38

Hover support is something we do plan to support and showing value of the variable on hover sounds like a great idea - I added that to https://github.com/hashicorp/terraform-ls/issues/87#issuecomment-650268823 which is our canonical issue for hover support.

**Comment by msaraceno** [comment]
Hi @radeksimko yes suggestions for completion of variable references like your example, these could be references to other resources as well for example if referencing a module or a data resource it should list available options and narrow down as you type. 
```
module "foo" {
  source = "app.terraform.io/org/workspace"
  verion = "0.0.1"
}

resource "bla_blah" "name" {
  attribute = module.<foo>.attribute
}
```

**Comment by radeksimko** [comment]
Initial support for references was added in (now merged) https://github.com/hashicorp/terraform-ls/pull/485 which will be released in coming days. The same PR also includes some description of features added and links to follow-up issues covering features which were omitted from that initial PR.

With that in mind I'm going to close this issue - do keep an eye out for the upcoming update (0.17.0).
