### ISSUE TITLE
terraform-ls is crashing on hover over variable inside locals block

### ISSUE THREAD

**Issue by flurie** [hashicorp/terraform-ls#317]
### Server Version

```
0.10.0
```

### Terraform Version

```
0.13.5
```

### Client Version

```
GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.4.0, Carbon Version 162 AppKit 1894.4) of 2020-11-22 (using emacs-lsp client version 7.1.0)
```

### Terraform Configuration Files

```hcl
locals {
  test_domain = "test.employerawsdev.com"
}
```

### Log Output

https://gist.github.com/flurie/491859d2577409b22bc4a865e72970f0

### Expected Behavior

The server should handle the hover gracefully.
### Actual Behavior

The server handled the hover ungracefully.

### Steps to Reproduce

1. Create a single terraform file with a `locals` block and add a variable of your choosing.
2. Start the langserver and client in the specified editor, ensuring that `lsp-ui-doc-mode` is enabled
3. Create a hover event on the variable inside the `locals` block. I triggered a hover event with the cursor in emacs.

**Comment by radeksimko** [comment]
Hi @flurie 
Thank you for the report.

The language server certainly shouldn't be crashing, but my suspicion based on the snippet of log you provided is that this may not be related to any particular position, but that the crash is caused by some missing data in client capabilities which were sent (or rather not sent) before you attempted the hover.

Can you provide us the whole log, or at least the part which starts with `Checking request for "initialize":`? That might help with shedding some light on this.

**Comment by flurie** [comment]
Hi @radeksimko
Absolutely. I reran it in a smaller scratch file as well that I was using to test some terraform builtins. This contains only locals and an output.

test file:
https://gist.github.com/flurie/44a7c83f69b4008231f942d20737640e

log output from beginning of server start:
https://gist.github.com/flurie/06c16975b9d78080e3b2a117f22aa748

Please let me know if you need anything else.
