### ISSUE TITLE
Add support for nested "examples"

### ISSUE THREAD

**Issue by iancward** [hashicorp/terraform-ls#330]
### Current Version
```
$ terraform ls --version
Terraform v0.12.29
+ provider.aws v3.19.0
+ provider.random v3.0.0
+ provider.template v2.2.0
```

### Use-cases
When we create a consumable module (say, for example, to provide an auto scaling group or an EBS volume), we generally set up the path like this:
```
.
├── CHANGELOG.md
├── examples
│   ├── example1
│   │   ├── main.tf
│   │   └── README.md
│   └── example2
│       ├── main.tf
│       └── README.md
├── main.tf
├── outputs.tf
├── README.md
└── variables.tf
```

But, this causes the terraform language server to throw an error that "Alternative root modules found for <module>. You can try setting paths to root modules explicitly in settings."

### Attempted Solutions
In my project directory, I created `.vscode/settings.json`  and put the following in it:
```json
{
    "terraform-ls.rootModules": [
        ".",
        "examples/example1",
        "examples/example2"
    ]
}
```
However, I still get the same error.

### Proposal
Please add support for this folder structure, which seems to follow "best practices" of providing examples on how to use the code. We also use these examples in CI/CD in order to test functionality of the module being created.

### References
https://github.com/hashicorp/vscode-terraform/issues/524

**Comment by radeksimko** [comment]
Hi @iancward 
Sorry for the confusion, but to my knowledge this exact example works. In fact the popup message you get proves that it's been loaded.

The message in itself is not an error, but a warning:
https://github.com/hashicorp/terraform-ls/blob/29e6ee9a953645ef20d7f58a1842ed2ee488a7e0/internal/langserver/handlers/did_open.go#L97-L104
We could downgrade it to an info level, but from what I can tell this probably wouldn't reduce the confusion too much as that just affects what icon is displayed near the message:

![Screenshot 2021-01-05 at 10 47 37](https://user-images.githubusercontent.com/287584/103637628-ac79d200-4f43-11eb-8f75-32da4c935065.png)
![Screenshot 2021-01-05 at 10 49 08](https://user-images.githubusercontent.com/287584/103637638-aedc2c00-4f43-11eb-974d-e3bf1867ad87.png)

Am I right in saying that it's the wording that confuses you and the fact that it's not obvious how to "fix it"?
We use the term "root module" throughout the terraform.io docs, but as it turns out this terminology isn't as well known and neither are the implications of module nesting/calling.

It is difficult to tell how you structured your hierarchy based on `example` names, but I can see it is similar to the hierarchy we have in our testdata here: https://github.com/hashicorp/terraform-ls/tree/main/internal/terraform/rootmodule/testdata/main-module-multienv Either way you'd likely want to only list the path to a single, or a handful of modules which are in fact "root" (meaning you regularly run `terraform init` for those), probably not all of them, like you seemed to have:

```
        ".",
        "examples/example1",
        "examples/example2"
```

--- 

Generally speaking though I have created https://github.com/hashicorp/terraform-ls/issues/354 to explain this problem in more detail and laid out the plan to removing this warning along with the other common one (`No root module found`). With that in mind I would suggest subscribing to that issue as I'm going to close this one.

**Comment by iancward** [comment]
Hi @radeksimko, `examples` there are are full terraform projects which include the parent folder. My `examples` folder is probably closer to the `testdata` directory in the code you linked.
I thought that by adding what I did to `settings.json` would suppress the error.

Also, I would see that error about 4-5 times and then Visual Studio Code would tell me that terraform-ls had crashed several times and would not be restarted. However, it's not been doing that lately (I think VS Code might have asked me to upgrade terraform-ls at some point).

**Comment by radeksimko** [comment]
@iancward Any time you see a crash I would suggest looking into the Outputs tab -> switching to `terraform-ls`, scrolling down to find the stack trace or anything that begins with `panic:` and opening a new issue. We would be more than happy to look into it and get it fixed! 😃 

I have doubts though that a complex hierarchy in particular would cause a crash.
