### ISSUE TITLE
[Feature Request] Code completion for resource types available

### ISSUE THREAD

**Issue by mattwelke** [hashicorp/terraform-ls#339]
I like how I can get code completion for attributes for a resource (by typing the first letter or using ctrl-space), but it would be nice too if I had code completion for when I begin typing `resource "<prefix>...` to help me type a resource that exists in one of my providers. Preferably, I could then hit tab to choose a name for the resource, then hit tab again to have it fill in every required attribute with placeholder values.

For example, I have the AWS provider (version `3.6`) installed. If I type like this, and then hit ctrl-space:

![image](https://user-images.githubusercontent.com/7719209/97938392-4c9e5980-1d4f-11eb-9389-0a24cebe5c02.png)

I get help that is okay, because it can reference strings from my project, but nothing smart from the providers. I'd like if it suggested things like `aws_ami` or `aws_instance`.

**Comment by radeksimko** [comment]
I will just clarify here, that in VS Code specifically it is possible to have labels, such as `aws_instance` in `resource` block, completed automatically, if you choose to also complete the block itself.

![2021-02-24 15 36 46](https://user-images.githubusercontent.com/287584/109025478-ab992d00-76b6-11eb-93f0-1f4997466fba.gif)

This is done by automatically triggering the completion from the server side. However there is no general support for such mechanism (yet) in LSP and most clients will probably prevent on-type completion within double quotes, because they (reasonably) assume it's just arbitrary literal string.

What does _not_ work at this point - and that is the reason I'd like to still keep this issue open - is when you type the above all by hand:

![2021-02-24 15 37 15](https://user-images.githubusercontent.com/287584/109026089-44c84380-76b7-11eb-83d3-d3eec256cea7.gif)

**Comment by mattwelke** [comment]
Ohh interesting. I can see now that people all have slightly different ways of coding and where they expect to leverage code completion features. For me, I usually type something out in full if I remember it (I can easily remember `resource "`) and then try to activate code completion when I get to a point where I don't remember stuff (I can't easily remember every possibly Terraform resource given the providers I have installed, especially as I'm learning Terraform). My technique prevents the code completion from being triggered properly.

**Comment by radeksimko** [comment]
Just to be clear I wasn't suggesting this is common or correct technique, just a technique that works within the limitations of the [LSP](https://microsoft.github.io/language-server-protocol/).

This is one of the relevant upstream issues discussing the problem: https://github.com/microsoft/language-server-protocol/issues/565 and this is where the current workaround was implemented: https://github.com/hashicorp/terraform-ls/pull/300

**Comment by mattwelke** [comment]
Understood. I was just doing a brain dump in case it helps the DX folks who end up addressing this.

**Comment by radeksimko** [comment]
In the interest of tracking a feature in one place I'm going to close this in favour of the following issues:
 - https://github.com/hashicorp/terraform-ls/issues/57
 - https://github.com/hashicorp/terraform-ls/issues/96
 - https://github.com/hashicorp/vscode-terraform/issues/397

Thank you for understanding.
