### ISSUE TITLE
Implement terraform plan and apply using workspace/executeCommand

### ISSUE THREAD

**Issue by aeschright** [hashicorp/terraform-ls#377]
### Current Version

```
v0.12.1
```

### Use-cases

A user should be able to run `terraform plan` and `terraform apply` in the same manner as `terraform init`, for a given module (directory).

### Attempted Solutions

Currently the only option is to open a terminal and run the commands there.

### Related LSP methods

`workspace/executeCommand`

### References

https://github.com/hashicorp/vscode-terraform/issues/541

**Comment by radeksimko** [comment]
As discussed on Slack and Zoom, this will be implemented on the client side as that gives us opportunity to provide more meaningful UX where output can be presented to the user.

Otherwise we'd be limited to LSP's methods, which includes unformattable popup messages or implementing our own method to "stream" the (possibly coloured) stdout/stderr somehow back to the client.
