### ISSUE TITLE
TestLangServer_workspaceExecuteCommand_modules_multiple fails on aarch64

### ISSUE THREAD

**Issue by 06kellyjac** [hashicorp/terraform-ls#549]
### Server Version

```
v0.18.0
```

### Terraform Version

```
None
```

### Client Version

```
None
```

### Terraform Configuration Files

```hcl
None
```

### Log Output

Gist contains: Just the error section, full aarch64 failing build, and a full x86 passing build for comparison

https://gist.github.com/06kellyjac/a5699a23c1745911eaf981a28c14a467

### Expected Behavior

Tests should pass

### Actual Behavior

`TestLangServer_workspaceExecuteCommand_modules_multiple` fails but only on aarch64

### Steps to Reproduce

Either run the tests normally from this repo on an **aarch64** machine (`go test ./...` or `go test github.com/hashicorp/terraform-ls/internal/langserver/handlers`)
Or clone my nixpkgs repo and use branch `terraform-ls` on an **aarch64** machine and run `nix-build -A terraform-ls`

**Comment by radeksimko** [comment]
Hi @06kellyjac 
Thanks for the report.

Unfortunately it seems that GitHub does not provide any ARM environment to run the tests in currently: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources which seems to be mostly blocked on lack of ARM support in Azure per https://github.com/actions/virtual-environments/issues/2552#issuecomment-771478000

We could in theory self host the ARM runners as per https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/ but that is obviously not as trivial (from ops perspective) as using GitHub-hosted runners.

I'm asking around internally (at HashiCorp) about that possibility, but generally until we have a way of testing this in CI it's unlikely that we'll find time to fix it.

That said if you can come up with a PR that fixes the test I'd be happy to review it!

**Comment by 06kellyjac** [comment]
Might be able to set up the tests in actions using QEMU like deno does using this: https://github.com/denoland/rusty_v8/blob/main/.github/workflows/ci.yml#L81-L96

I imagine it'll need some adapting to work for golang rather than rust but I might play with it

**Comment by radeksimko** [comment]
I had a spare moment today to reproduce this on my Raspberry Pi and I have a hunch of what the root cause is.

I believe it's merely test data being limited to 3 combinations of OS & architecture:

https://github.com/hashicorp/terraform-ls/tree/main/internal/terraform/module/testdata/main-module-multienv/env/dev/.terraform/plugins

I reckon the best way forward would be to turn this test into more E2E test which actually calls Terraform and runs `init` on whatever platform the test is running on and creates the cache relevant for that platform, instead of maintaining cache in-tree.
