### ISSUE TITLE
Separate language IDs for .tf and .tfvars

### ISSUE THREAD

**Issue by rchl** [hashicorp/terraform-ls#556]
Not necessarily a bug but more of a question/discussion.

I've noticed that the support for *.tfvars was added in https://github.com/hashicorp/terraform-ls/commit/9b1ed216eacdf1be241d7e331e4a423182e7edae

My question is related to the choice of introducing a different languageID for that file type. Was it necessary?

In Sublime Text at least, the choice of ID is strictly connected to the syntax definition that is used for parsing the file and in ST both *.tf and *.tfvars extensions use the same syntax. That makes it impossible (at least without hacks) to pass different language ID for tfvars.

Is there really a good reason to assign different language IDs to those extensions?

(Note that possible way to fix it in ST would be to split the syntax definition into multiple syntaxes though it might feel redundant if it's just for the sake of the language server.)

CC @beandrad

**Comment by beandrad** [comment]
*.tfvars files are used to set the values of the variables defined in the Terraform module (in *.tf files). This is important from the point of view of the language server as, for instance, the completion candidates for *.tfvars (the module input variables) are different from the completion candidates returned for *.tf files. 

In order to identify the file "type" and return the corresponding results on completion/hover/highlighting, the language server uses the file language ID.

**Comment by radeksimko** [comment]
Hi @rchl !
Good question. The short answer is yes - this is very much intentional and necessary, as @beandrad explained.

We are still working through the list of other file extensions that are being slowly standardized and language IDs will be assigned to those as well. This is probably the most up-to-date list currently:
https://github.com/hashicorp/vscode-terraform/issues/636

This is a relevant docs update: https://github.com/hashicorp/terraform/pull/28924

I am aware that most (if not all) existing editor plugins only use a single languageID and I anticipated this being a problem when planning out the work on tfvars in May 2020: https://github.com/hashicorp/terraform-ls/issues/50#issuecomment-630053301 I could have been more upfront about it and raise issues in relevant places but frankly it wasn't decided until very recently what exact language ID will we use and how is it going to fit into the whole Terraform ecosystem and other HashiCorp tools.

This was a subject of an internal RFC process, which I will attempt to summarize below.

### Client-side Highlighting

For the purposes of highlighting it is usually enough to say that a document uses HCL-based language and the same **HCL grammar** can be used to highlight any `*.tf`, `*.tfvars` or `*.pkr.hcl` or any other HCL documents. The assumption here is though that such grammar contains _all_ HCL features and does _not_ make any assumptions about the _schema_.

Schema in HCL basically defines what block types can be called, what attribute names are allowed within a block etc. In other words a good grammar should highlight the following:

```hcl
blablah "label1" "label2" {
  foo = "bar"
}
```
equally to
```hcl
resource "aws_instance" "ref_name" {
  ami = "ami-12345678"
}
```

Most grammars I have seen unfortunately do make assumptions about the schema and are then applied in situations where the schema differs. This leads to e.g. highlighting `resource` as a special keyword in `tfvars` where it doesn't really have any meaning - in fact any blocks are invalid in that file.

Another reason static grammars should not make these assumptions is because schema typically evolves in time and there are no way of accounting for these differences (i.e. serving different grammar based on TF version for example).

If a plugin's goal is _just_ to highlight code and _do nothing else_ then it can use `hcl` as a language ID and relevant HCL grammar.

### Language Server features

For any code assistance typically provided by an LS, such as completion, hover, go-to-definition, go-to-references etc. we do need to know more than just the fact that a document uses HCL based syntax. We need to know the schema.

Speaking of `tf` and `tfvars` in particular:

 - `tf` - here users expect `resource`, `data`, `terraform` blocks etc.
 - `tfvars` - here users expect variable names as "root" attributes, but _nothing else_

--- 

There are plans to develop a canonical HCL grammar which could be leveraged by the ST plugin and other tools/plugins, but this will take time and effort. This is also one of the reasons we're actively hiring for 2 more folks: https://github.com/hashicorp/terraform-ls/issues/534

See also:

 - https://github.com/hashicorp/terraform-ls/blob/main/docs/language-clients.md#language-ids
 - https://github.com/hashicorp/vscode-terraform/issues/638
 - https://github.com/hashicorp/vscode-terraform/issues/639
    - I think it would be relevant to also have a generic HCL Sublime Text plugin, although we don't have the near term plans to develop one at HashiCorp.

**Comment by rchl** [comment]
Thanks for thorough explanation. It does make sense in that case indeed and could be handled in https://github.com/alexlouden/Terraform.tmLanguage/issues/48 instead.
