### ISSUE TITLE
Many-root workspaces cause server to hang

### ISSUE THREAD

**Issue by chris-redekop** [hashicorp/terraform-ls#838]
### Server Version

```
0.26.0
```

### Terraform Version

```
Terraform v1.1.7
on linux_amd64
```

### Client Version

```
Visual Studio Code

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-104-generic
```

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.4.0"
    }
  }
}

resource "aws_s3_bucket" "bucket" {
}
```

### Log Output

https://gist.github.com/chris-redekop/b1e60b409cfa8641e02f54a05aa4a049

### Expected Behavior
The attached [test-3.zip](https://github.com/hashicorp/terraform-ls/files/8326359/test-3.zip) contains a workspace that demonstrates expected behaviour in a 3-root workspace.  After opening this workspace, the VS-Code extension works as expected and I can e.g. format Terraform files.

### Actual Behavior
The attached [test-100.zip](https://github.com/hashicorp/terraform-ls/files/8326360/test-100.zip) contains a workspace that demonstrates problem behaviour in a 100-root workspace.  After opening this workspace, [the terraform-ls logs stop at "watching for changes ..."](https://gist.github.com/chris-redekop/b1e60b409cfa8641e02f54a05aa4a049), and trying to format a Terraform file results in an error: There is no formatter for 'terraform' files installed.

### Steps to Reproduce
Open a many-root workspace, like the one in the attached zip file, and try to format a Terraform file.  Also [a Bash script](https://github.com/hashicorp/terraform-ls/files/8326358/generate-multi-root-workspace.zip) is attached.  It generates a workspace with a specified number of roots.  You might find it useful to create workspaces with different numbers of roots.
```
./generate-multi-root-workspace <n>
```

**Comment by radeksimko** [comment]
Hi @chris-redekop 
Thank you for the detailed bug report.

I was able to reproduce the behaviour you described.

--- 

Based on my preliminary brief debugging it looks like the root cause is some logic within the walker. Specifically I can see that it starts to block here

https://github.com/hashicorp/terraform-ls/blob/031e30f62ab169104837fbb1e9ef2633ded73329/internal/langserver/handlers/initialize.go#L217

after 50th workspace - which corresponds to this limit here:
https://github.com/hashicorp/terraform-ls/blob/031e30f62ab169104837fbb1e9ef2633ded73329/internal/terraform/module/walker.go#L65-L68

The problem here is the sequence of events in `initialize` handler where we 1st queue up all paths for walking and only once _all_ of them are in the queue, we start walking. These two operations could be independent of each other - i.e. we could continue adding to the queue _and_ walking at the same time. However such async logic makes testing all this more difficult.

So one solution would be probably an uncapped channel - the only downside I can think of is potentially high peak memory usage but (a) these are just relatively short strings of paths and (b) the channel should be consumed pretty quickly, unless the individual workspaces are also very deep

Alternative solution would be introducing some more sync primitives into the walker which would be conditional either in the "prod" version we ship or the mocked version of walker.

Let me have a think about this...

**Comment by radeksimko** [comment]
@chris-redekop I appreciate the repro case with 100 workspaces but I'm curious - is this how you ran into this bug? i.e. do you genuinely have 100 workspaces open in VS Code regularly? We plan to do some benchmarking and it would help us a ton to benchmark some realistic usage and know what that is.

**Comment by radeksimko** [comment]
I actually managed to find a solution which still keeps the code testable because we have the sync primitives within `StartWalking()`, so all good: https://github.com/hashicorp/terraform-ls/pull/839

**Comment by chris-redekop** [comment]
Thanks, @radeksimko , that's good news!

> I appreciate the repro case with 100 workspaces but I'm curious - is this how you ran into this bug? i.e. do you genuinely have 100 workspaces open in VS Code regularly? We plan to do some benchmarking and it would help us a ton to benchmark some realistic usage and know what that is.

I went back to my real-world workspace and counted _53_ roots.  My scenario is a single workspace with all of my Terraform deployment projects + all of the Terraform module projects that support the deployment projects.

Thanks again
