### ISSUE TITLE
feat: go to definition on modules

### ISSUE THREAD

**Issue by astorath** [hashicorp/terraform-ls#95]
It would be very helpful to have an options to:
1. go to variable definitions from module statement params to module source,
2. go to module dir from module `source` statement.

**Comment by radeksimko** [comment]
I may create a parent issue for the overall support of "go to definition" and list all the contexts where this may be useful, but yes - module and the contexts you outlined is where "go to definition" certainly makes sense. 👍

**Comment by radeksimko** [comment]
Also I should note that before a module can be edited in IDE with any "help" (like completion, hover, go-to-definition, or any other features) it will need to be `terraform init`'d, otherwise the language server has no way of getting the data for these features because the providers aren't available to provide the schema.

We plan to make this a bit more obvious per https://github.com/hashicorp/terraform-ls/issues/83

**Comment by radeksimko** [comment]
I have created individual issues to track mentioned functionality here with some more details:

1. https://github.com/hashicorp/vscode-terraform/issues/670
2. https://github.com/hashicorp/vscode-terraform/issues/669

Tracking these separately will help us plan the work on our roadmap as smaller chunks.

With that in mind I'm going to close this issue.

Thanks for the ideas!
