### ISSUE TITLE
feat: required arguments pre-filled when creating resource

### ISSUE THREAD

**Issue by mazingerzzz** [hashicorp/terraform-ls#96]
It would be awesome to have pre-filled  required arguments when created new ressource.

**Comment by radeksimko** [comment]
Agreed - this would be a useful feature to have.

This could be implemented as part of the completion method via snippets:

https://github.com/hashicorp/terraform-ls/blob/b1c85b958b1673ccd30c21cd7c25732c6252b071/internal/terraform/lang/schema.go#L11-L45

with that the required arguments would be pre-filled automatically after picking the type

![Screenshot 2020-05-12 at 20 56 16](https://user-images.githubusercontent.com/287584/81739336-131d1d80-9493-11ea-8226-42be411271dc.png)

There's just one edge which comes to my mind - what happens if there are already existing attributes within the block? Should we remove all of these and replace them with new ones which are relevant for the new picked type? I think it's important to understand why/when would this happen - it may be because the user made a mistake when picking the type at first and triggered completion again, or it could be because they are migrating away from a deprecated resource name (e.g. `aws_lb` -> `aws_alb`). I think the second use case could probably eventually be dealt with by Terraform's own CLI as it also has the power to move resources within state.

So I'm leaning more towards just replacing whatever there may be inside the block with new required arguments, but I'm keen to hear about other use cases where this may not be appropriate.

**Comment by FernandoMiguel** [comment]
replace only if file is saved is probably a good idea, so the user can revert if they dont want that.

and if possible, if auto-save is on (i do), only if committed

**Comment by danieldreier** [comment]
my impulse for the least-surprising or least-destructive would be to strictly add the required attributes/blocks without removing the old ones, and count on other validations to notify the user if they end up with unwanted attributes that no longer fit the resource. 

For example, in the use case where I'm refactoring a resource from old name/attributes to the new, it would be annoying to lose everything, because I might want to reference the known-invalid syntax to copy/refactor an expression, reference, etc.

**Comment by radeksimko** [comment]
We have also discussed the possibility of pre-filling required attributes via code action, which may be the most flexible option here.

Example from gopls:

![2021-07-23 15 32 46](https://user-images.githubusercontent.com/287584/126799179-dd5a7450-8033-462a-aee3-92b71fa638c9.gif)

**Comment by radeksimko** [comment]
@jpogran implemented this as part of the following PRs which will be part of the upcoming LS / extension release:

 - https://github.com/hashicorp/terraform-ls/pull/657
 - https://github.com/hashicorp/vscode-terraform/pull/799

As mentioned within these issues, the functionality will be (at least initially) opt-in via `prefillRequiredFields` config option under `terraform-ls.experimentalFeatures`.

We also plan to add code action that would provide comparable functionality for _existing_ blocks, which is tracked under https://github.com/hashicorp/vscode-terraform/issues/801
