### ISSUE TITLE
signatureHelpProvider returns empty response

### ISSUE THREAD

**Issue by jemag** [hashicorp/terraform-ls#985]
### Server Version

```
v.0.28.1

```

### Terraform Version

```
Terraform v0.14.10

```

### Client Version

```
Neovim (NVIM v0.8.0-dev+537-gffbed8d6c)
```

### Log Output
https://gist.github.com/cb9737660e034ef2b4430b7bf5702c45

### Expected Behavior
SignatureHelpProvider capabilities returns nothing

### Actual Behavior
SignatureHelpProvider returns empty response

### Steps to Reproduce

1. Open any terraform file
2. Notice SignatureHelpProvider capability response

### Notes

It seems that currently signature help is not supported (https://github.com/hashicorp/terraform-ls/issues/857). However, the server currently seems to return an empty response instead of simply returning nothing.

This makes it hard for clients of the server to guess if the capability is actually supported or not. See : https://github.com/neovim/neovim/issues/18939

From that issue, to add context:
> See [microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_formatting](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_formatting) for an example. That also makes me think that an empty dict must not be treated as falsy because DocumentFormattingOptions doesn't even have any properties

**Comment by radeksimko** [comment]
Hi @jemag 
Thanks for the report.

This looks like an effect of the Go bindings for LSP which we leverage from gopls, or rather the unfortunate effect of these bindings being generated from TypeScript where a field/variable can freely change type while still communicating the subset of types that are supported.

https://github.com/hashicorp/terraform-ls/blob/14e71fdfbe8e98e4d0d885419113ed3cb850ab84/internal/protocol/protocol.go#L4319-L4322

This of course doesn't translate that well into any strongly typed language such as Go, so gopls maintainers already used `interface{}` (any type) to account for this.

The only reason this likely doesn't affect gopls is because it already implements that `signatureHelp` capability, so that struct is never empty.

We could either send a patch upstream to gopls, to fix the [logic which generates the Go bindings](https://github.com/golang/tools/tree/master/internal/lsp/protocol/typescript), and/or re-implement the whole `ServerCapabilities` struct internally.

As for a better long-term solution, LSP 3.17 finally introduced machine-readable spec. AFAIK nobody has yet tried to generate Go binding from that, but it's likely going to be much easier, cleaner and safer and it may eradicate problems like this.

--- 

The same problem likely applies to onTypeFormatting capability which we don't implement (yet)

https://github.com/hashicorp/terraform-ls/blob/14e71fdfbe8e98e4d0d885419113ed3cb850ab84/internal/protocol/protocol.go#L4381-L4384

**Comment by radeksimko** [comment]
Signature help was implemented as part of https://github.com/hashicorp/terraform-ls/pull/1077 and a number of other supporting PRs, so this should no longer be an issue. This is now part of the latest [v0.31.0](https://github.com/hashicorp/terraform-ls/releases/tag/v0.31.0) release.

The other mentioned problem with `onTypeFormatting` is being addressed as another side effect of https://github.com/hashicorp/terraform-ls/pull/1256
